import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { DataQualityMetrics } from "@/components/data-quality-metrics"
import { MarketOverview } from "@/components/market-overview"
import { ClientSegmentation } from "@/components/client-segmentation"
import { RecentInsights } from "@/components/recent-insights"

export default function Dashboard() {
  return (
    <div className="flex-1 space-y-4 p-8 pt-6">
      <div className="flex items-center justify-between space-y-2">
        <h2 className="text-3xl font-bold tracking-tight">OkapIQ Analytics Dashboard</h2>
      </div>
      <Tabs defaultValue="overview" className="space-y-4">
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="analytics">Analytics</TabsTrigger>
          <TabsTrigger value="reports">Reports</TabsTrigger>
          <TabsTrigger value="clients">Clients</TabsTrigger>
        </TabsList>
        <TabsContent value="overview" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total SMBs Analyzed</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">33.2M</div>
                <p className="text-xs text-muted-foreground">99.9% of all U.S. businesses</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Economic Impact</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">44%</div>
                <p className="text-xs text-muted-foreground">of U.S. GDP generated by SMBs</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">PE Dry Powder</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">$2.3T</div>
                <p className="text-xs text-muted-foreground">targeting SMB acquisitions</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Data Accuracy</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">99.5%</div>
                <p className="text-xs text-muted-foreground">verified and validated data points</p>
              </CardContent>
            </Card>
          </div>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
            <Card className="col-span-4">
              <CardHeader>
                <CardTitle>Market Overview</CardTitle>
              </CardHeader>
              <CardContent className="pl-2">
                <MarketOverview />
              </CardContent>
            </Card>
            <Card className="col-span-3">
              <CardHeader>
                <CardTitle>Data Quality Metrics</CardTitle>
                <CardDescription>Validation and verification scores</CardDescription>
              </CardHeader>
              <CardContent>
                <DataQualityMetrics />
              </CardContent>
            </Card>
          </div>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
            <Card className="col-span-3">
              <CardHeader>
                <CardTitle>Client Segmentation</CardTitle>
                <CardDescription>Distribution by industry and use case</CardDescription>
              </CardHeader>
              <CardContent>
                <ClientSegmentation />
              </CardContent>
            </Card>
            <Card className="col-span-4">
              <CardHeader>
                <CardTitle>Recent Insights</CardTitle>
                <CardDescription>Latest data-driven findings</CardDescription>
              </CardHeader>
              <CardContent>
                <RecentInsights />
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  )
}
